### ISSUE TITLE
[WEBSITE] Supply Chain/Dependency Management

### ISSUE THREAD

**Issue by boltdynamics** [xplorer-io/security#1]
Look at implementing https://snyk.io/

Pair with @samirkandel @DipeshGainju @newton please

**Comment by samurato** [comment]
- [ ] Investigate Snyk tools and product @samirkandel @DipeshGainju @enj33 
- [ ] Open Snyk account with Xploreres domain 
- [ ] Create Integration with the repo and Snyk for software dependency scanning
- [ ] Integrate with Slack and notify of any vulnerabilities Identified. 
- [ ] Create an action plan for remediation

**Comment by DipeshGainju** [comment]
Hi @samurato
It says there is no issues in json package, 
![Image](https://github.com/user-attachments/assets/e624e62a-db4b-4594-a868-36f56ee6f3b1)

**Comment by samurato** [comment]
@DipeshGainju is it still showing the same. It takes a while to finish analysis

**Comment by samurato** [comment]
if not then that's good. No vulnerabilities
:)

**Comment by DipeshGainju** [comment]
Hi @samurato 
Just found this new vulnerabilities in our repo
![Image](https://github.com/user-attachments/assets/6a9aa420-065d-4c10-a87b-390252fa4311)
